In [10]:
import numpy as np
import pandas as pd
from IPython.display import display

In [13]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
display(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [14]:
#--------SQUARE EVERY ELEMENT IN FIRST COLUMN------------#

def square(x):
    square = x**2
    return square

squared_B_df1 = df1['B'].apply(square)

In [15]:
# changes are not made yet so make the actual dataframe change..
display(df1)

df1['B'] = squared_B_df1 

display(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [19]:
#-----------CREATE NEW COLUMN D WITH SQUARES OF ELEMENTS OF C---------#
def square(x):
    square = x**2
    return square
 
df1['D'] = df1['B'].apply(square)
display(df1['D'])
display(df1)

0      10000
1     160000
2     810000
3    2560000
4    6250000
Name: D, dtype: int64

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000