In [21]:
import numpy as np
import pandas as pd
from IPython.display import display

In [22]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
display(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [23]:
#----------- ADD 10 IN FIRST COLUMN [ 'A' ]-----------#

display(df1['A']+10)
display(df1)

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [24]:
#---------MULTIPLY BY 2 IN SECOND COLUMN-------------#

display(df1['B']*2)
display(df1)  # still stays the same as above line creates a copy and does not touch the original array

0     20
1     40
2     60
3     80
4    100
Name: B, dtype: int64

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [25]:
# -------------ADD 20 IN FIRST TWO COLUMNS----------#

display(df1)
display(df1[['A','B']] + 20)
display(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

    A   B
0  21  30
1  22  40
2  23  50
3  24  60
4  25  70

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [26]:
# ----------ADD 10 IN FIRST ROW-------------#

display(df1.loc[[1]]+10)

    A   B    C
1  12  30  210

In [27]:
# ADD 20 IN FIRST AND SECOND ROW 

# index 0 and 1 --> 20 add
display(df1.loc[[0,1]]+20)

    A   B    C
0  21  30  120
1  22  40  220