In [4]:
import pandas as pd
import numpy as np
from IPython.display import display

In [5]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
display(df)

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
#------------ALL SALES STATISTICAL OPERATIONS---------------#

sales = df['Sales']
display(sales)

sales.agg(['sum' , 'mean' , 'min' , 'max' , 'count' , 'std' , 'median','var'])

0    100
1    200
2    150
3    250
4    120
5    180
6    200
7    300
Name: Sales, dtype: int64

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
var       4364.285714
Name: Sales, dtype: float64

In [7]:
# --- ALL STATISTICAL OPERATIONS ON SALES GROUPED BY CATEGROY-------#

grp_by_cat = df.groupby('Category')
for cat1 , cat2 in grp_by_cat:
    display(cat1 ,cat2 )

sales_grp_by_cat = grp_by_cat['Sales']
for cat1 , cat2 in sales_grp_by_cat:
    display(cat1,cat2)

sales_grp_by_cat.agg(['sum' , 'mean' , 'min' , 'max' , 'count' , 'std' , 'median','var'])

'A'

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07

'B'

  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

'A'

0    100
2    150
4    120
6    200
Name: Sales, dtype: int64

'B'

1    200
3    250
5    180
7    300
Name: Sales, dtype: int64

          sum   mean  min  max  count        std  median          var
Category
A         570  142.5  100  200      4  43.493295   135.0  1891.666667
B         930  232.5  180  300      4  53.774219   225.0  2891.666667

In [8]:
# --- ALL STATISTICAL OPERATIONS ON SALES GROUPED BY CATEGORY AND STORES---------#

grp_by_cat_store = df.groupby(['Category','Store'])
for cat1,cat2 in grp_by_cat_store:
    display(cat1,cat2)

('A', 'S1')

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
4        A    S1    120         8 2023-01-05

('A', 'S2')

  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
6        A    S2    200        15 2023-01-07

('B', 'S1')

  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
7        B    S1    300        25 2023-01-08

('B', 'S2')

  Category Store  Sales  Quantity       Date
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06

In [9]:
sales_grp_by_cat_store = grp_by_cat_store['Sales']

for cat1,cat2 in sales_grp_by_cat_store:
    display(cat1,cat2)

('A', 'S1')

0    100
4    120
Name: Sales, dtype: int64

('A', 'S2')

2    150
6    200
Name: Sales, dtype: int64

('B', 'S1')

1    200
7    300
Name: Sales, dtype: int64

('B', 'S2')

3    250
5    180
Name: Sales, dtype: int64

In [10]:
display(sales_grp_by_cat_store.agg(['sum' , 'mean' , 'min' , 'max' , 'count' , 'std' , 'median','var']))

                sum   mean  min  max  count        std  median     var
Category Store
A        S1     220  110.0  100  120      2  14.142136   110.0   200.0
         S2     350  175.0  150  200      2  35.355339   175.0  1250.0
B        S1     500  250.0  200  300      2  70.710678   250.0  5000.0
         S2     430  215.0  180  250      2  49.497475   215.0  2450.0