In [3]:
import pandas as pd
import numpy as np
from IPython.display import display

In [4]:
# Show all columns without truncation
pd.set_option('display.max_columns', None)

# Limit the number of rows shown (prevents a wall of text)
pd.set_option('display.max_rows', 100)

# Set the max width of a column (prevents long text from stretching the table)
pd.set_option('display.max_colwidth', 100)

# Reduce the decimal places for cleaner numbers
pd.set_option('display.precision', 2)

In [5]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
display(df)

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
# Group by category and calculate  : SUM , AVERAGE , STD DEVIATION , VARIANCE --> SALES

grp_cat  = df.groupby('Category')
display(grp_cat)
print("\n")
# we cant view group by , output will be : new object created at some address

for cat1,cat2 in grp_cat:
    display(cat1)
    display(cat2)

'A'

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07

'B'

  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [7]:
#-----------CALCULATE SUM , AVG , MEAN , VARIANCE...
grp_cat = df.groupby('Category')

display(grp_cat['Sales'].sum())

print("\nMean: ")
display(grp_cat['Sales'].mean())

print("\nStandard Deviation: ")
display(grp_cat['Sales'].std())

print("\nVariance: ")
display(grp_cat['Sales'].var())

Category
A    570
B    930
Name: Sales, dtype: int64

Mean:

Category
A    142.5
B    232.5
Name: Sales, dtype: float64

Standard Deviation:

Category
A    43.49
B    53.77
Name: Sales, dtype: float64

Variance:

Category
A    1891.67
B    2891.67
Name: Sales, dtype: float64

In [12]:
#---------------GROUP BY STORES AND :  SUM , AVG --> SALES-------------#

grp_stores = df.groupby('Store')
for s1,s2 in grp_stores : 
    display(s1)
    display(s2)

'S1'

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
4        A    S1    120         8 2023-01-05
7        B    S1    300        25 2023-01-08

'S2'

  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07

In [13]:
#-----------SUM , AVG ----------#

display(grp_stores['Sales'].sum())

print("\n")
display(grp_stores['Sales'].mean())

Store
S1    720
S2    780
Name: Sales, dtype: int64

Store
S1    180.0
S2    195.0
Name: Sales, dtype: float64

In [14]:
#----------GROUP BY STORE AND CATEGORY : --> SALES SUM -------------#

# TWO TYPES OF DATA : QUALITATIVE AND QUANTATIVE DATA 
# QUALITATIVE DATA : CATEGORICAL DATA  ( Stores ,  category , male female ....)
# QUANTATIVE DATA :  (quant_in_stock , date of sale , sales )

# We use group by for categorical data..


grp_cat_store = df.groupby(['Category', 'Store'])
display(grp_cat_store['Sales'].sum())

print("\n")
grp_store_cat = df.groupby(['Store', 'Category'])
display(grp_store_cat['Sales'].sum())

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64