In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
display(df)
df = pd.DataFrame(data.values(), index=data.keys()).T
display(df)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [13]:
 #----------------FILLING MISSING VALUES ACROSS WHOLE DATAFRAME----------------#

display(df.fillna(value = 0))

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [14]:
#---------------FILLING MISSING VALUES COLUMN WISE----------------------#

values_to_fill = {
    'A' : 1000,
    'B' : 2000,
    'C' : 3000,
    'D' : 4000
}

# REMEMBER WHILE FILLING MISSING VALUES  COLUMN WISE 
# WE USE DICTIONARY WITH KEYS AS COLUMNS AND VALUES AS REPLACEMENTS OF NULL IN THAT COLUMN..
display(df.fillna(value = values_to_fill))

display(df) # still the same ..

values_to_fill = {
    'A' : 'a',
    'B' : 'b',
    'C' : 'c',
    'D' : 'd'
}
display(df.fillna(value = values_to_fill))

        A    B       C       D
0     1.0  1.0     1.0     1.0
1     2.0  2.0     2.0  4000.0
2  1000.0  3.0     3.0  4000.0
3     4.0  4.0  3000.0  4000.0
4     5.0  5.0  3000.0     5.0

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0    d
2    a  3.0  3.0    d
3  4.0  4.0    c    d
4  5.0  5.0    c  5.0