In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [11]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
display(df)
df = pd.DataFrame(data.values(), index=data.keys()).T
display(df)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [20]:
#--------------------TO FIND NULL VALUES AND ITS SUM ACROSS WHOLE DATA(BOOL)-------------------#

bool_isna = df.isna()
display(bool_isna)

df.isna().sum() # gives how many null values in each column 

# We will have 100 Columns so to find columns which have some missing values or not 
# meaning to find the columns which have atleast one missing value 

df.isna().any() # for every column true or false for presence of missing values

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

A    True
B    True
C    True
D    True
dtype: bool