In [6]:
import pandas as pd
import numpy as np
from IPython.display import display

In [7]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
display(df)
df = pd.DataFrame(data.values(), index=data.keys()).T
display(df)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [10]:
#--------------TO VIEW ROWS WITHOUT MISSING DATA-----------#

display(df.dropna()) # all rows without missing values # by default thresh = 4

     A    B    C    D
0  1.0  1.0  1.0  1.0

In [18]:
#-----------------ADDING THRESHOLS WITH DROPPING ROWS-------------#

display(df.dropna(thresh=3)) # dropna measn dropping null so accessing not null values 

display(df.dropna(thresh=1)) # all rows which have atleast one non null values.....

display(df.dropna(thresh=4)) 

display(df.dropna(thresh=5)) 

# thresh = 3 atleast 3 not null values as dropna means dropping null values

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

     A    B    C    D
0  1.0  1.0  1.0  1.0

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [20]:
display(df)
# inplace =  true is never used in this notebook so original data remains safe......

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0