In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [3]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name" , "Age" , "City" , "Salary"]
df2 = pd.DataFrame(data_list)
display(df2)
df2 = pd.DataFrame(data_list , columns = columns) # every tuple as a list 
display(df2)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
#----------------CONDITIONAL SELECTION----------------#

# SELECT PEOPLE AGED ABOVE 30...

bool_age = df2['Age']>30
display(bool_age)
df2[bool_age]

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [21]:
# SELECT PEOPLE AGED ABOVE 30 AND SALARY >75000

display(df2)

# bool_age_salary = df2['Age']>30 & df2['Salary']>75000 || WHY THIS IS WRONG
# BOOL OPERATI0N MUST RESULT IN TRUE OR FALSE (TRUE) AND (TRUE) BRAKCETS MUST BE ASSIGNED 

bool_age_salary = (df2['Age']>30) & (df2['Salary']>75000)
print(bool_age_salary)
i=0
for bool_value in bool_age_salary:
    if bool_value ==True:
        print("Salary>75000 and age>30 for index: ",i)
        i = i+1
    else:
        print("Not Valid for index  :             " ,i)
        i = i+1

display(df2[bool_age_salary])

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

0    False
1    False
2    False
3     True
dtype: bool
Not Valid for index  :              0
Not Valid for index  :              1
Not Valid for index  :              2
Salary>75000 and age>30 for index:  3

    Name  Age    City  Salary
3  Linda   42  London   85000