In [59]:
import pandas as pd
import numpy as np
from IPython.display import display

In [60]:
#-----------------TO CREATE NEW COLUMN-------------#

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name" , "Age" , "City" , "Salary"]
df2 = pd.DataFrame(data_list , columns=columns)
display()

In [61]:
# to create new column designation , we use dfictionary syntax where label is key and values is list of values

df2['Designation'] = ["Doctor" , " Engineer" , "Teacher" , "HR"]
display(df2)

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000          HR

In [62]:
#----------------TO REMOVE COLUMN---------------#

# NOTE: Unlike NumPy slicing, Pandas .drop() creates a NEW COPY by default.
# It does NOT point to the original memory; it allocates fresh space on D: drive/RAM.

# 1. This displays a temporary COPY (original df2 remains unchanged)
display(df2.drop('Designation', axis=1))


# AXIS =1 IS COLUMNS AND AXIS =0 IS ROW IN THIS ......
# IF I DONT WRTIE AXIS=1 , DEFAULT AXIS = 0 WHICH IS FOR ROWS.......


# 2. To modify the original, we MUST use 'inplace=True' or re-assign (df2 = df2.drop...)
# Modifying a dropped dataframe will NOT change the original because they are different objects.

# 3. Memory Logic: 
# NumPy Slice = View (Shared Memory)
# Pandas .drop() =  Copy (Separate Memory)
# Python List Slice = Shallow Copy (New List Object)

display(df2) # Confirms df2 is still the same because .drop() didn't touch it 

df2.drop('Designation',axis=1,inplace=True)
display(df2)

# or we can create a copy which without implace and assign it to original df2 df2  = df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000          HR

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [63]:


# NumPy Slice (arr[0:2])	    View	        Shared Memory. Changing the slice kills the original data.
# Pandas .drop()	            Deep Copy	    New Object. It allocates entirely new memory for the remaining columns.
# Python List Slice (l[0:2])	Shallow Copy	New List Object. But if the list contains objects (like other lists), those internal objects are still shared.

In [64]:
# -------------TO CREATE ROW-------------------#

df2[4] = 'Mike', 23, 'California', 80000 # this creates a new column with 4 as header
display(df2)

df2.drop(4,axis=1,inplace=True)
display(df2)

    Name  Age      City  Salary           4
0   John   28  New York   65000        Mike
1   Anna   34     Paris   70000          23
2  Peter   29    Berlin   62000  California
3  Linda   42    London   85000       80000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [65]:
#---------------TO VIEW , CREATE ROW---------------#

# df[4] --> refers to column label by default..
# df.loc[4] --> refers to index 4 of row labels

#--------VIEW-------#

print(df2.loc[1])
print('\n')
print(df2.loc[2])

display(df2)

df2.loc[4] = ['Mike', 23, 'California', 80000]

display(df2)

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object


Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

    Name  Age        City  Salary
0   John   28    New York   65000
1   Anna   34       Paris   70000
2  Peter   29      Berlin   62000
3  Linda   42      London   85000
4   Mike   23  California   80000

In [66]:
#--------------TO REMOVE ROW-------------------#

df2.drop(4,axis=0) # creates a new object we must use inplace = true or assign this new object to original one 
print("Without inplace: \n")
display(df2)

df2.drop(4,axis=0,inplace=True)
display(df2)

Without inplace:

    Name  Age        City  Salary
0   John   28    New York   65000
1   Anna   34       Paris   70000
2  Peter   29      Berlin   62000
3  Linda   42      London   85000
4   Mike   23  California   80000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [67]:
display(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000