In [36]:
import pandas as pd
import numpy as np
from IPython.display import display

In [37]:

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name" , "Age" , "City" , "Salary"]
df2 = pd.DataFrame(data_list)
display(df2)
df2 = pd.DataFrame(data_list , columns = columns)
display(df2)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
#------------------SELECTING  SINGLE ROW-----------------#

display(df2.loc[0])
print("\n")
display(df2.loc[2])

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

In [39]:
# ----------------SELECTING MULTIPLE ROWS---------------------#

display(df2)

display(df2.loc[[0,1]]) # for multiple rows viewing we pass list of lists of row labels or indexes of that rows 
display(df2.loc[[1,2,3]])

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [44]:
#----------VIEWING SPECIFIC COLUMNS OF SPECIFIC ROWS---------------#

display(df2)

display(df2.loc[[1,2,3]]['Name'])

display(df2.loc[[1,2]][['City' , 'Salary']])

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

     City  Salary
1   Paris   70000
2  Berlin   62000