In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

In [2]:
# First Dataframe
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

display(df1 , df2)

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75

In [10]:
#------------------JOIN DATAFRAMES------------------#

# pd.merge(df1,df2) wont work as there is no common attrbute (column )on which we can join


display(df1.join(df2,how='outer'))

display(df1.join(df2,how='left'))

display(df1.join(df2,how='right'))

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

      name  score
2      Bob     85
3  Charlie     90
4      NaN     75

In [14]:
# SIIMILARY , 

display(df1 , df2)

display(df2.join(df1,how='outer'))

display(df2.join(df1,how='left'))

display(df2.join(df1,how='right'))

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie